name: Release

on:
  push:
    tags:
      - '*'

jobs:
  analyse:
    name: Security analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Initialise CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  build:
    needs: analyse
    name: Build and release package to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip|3.8|${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
      - name: Build packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload packages to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
